name: Build and Sign Release APK

on:
  release:
    types:
      - published

jobs:
  build:
    name: Build and Sign APK
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17' # Adjust to your project Java version

      # Step 3: Decode and save the keystore file
      - name: Decode keystore
        run: |
          echo "$KEYSTORE_BASE64" | base64 -d > key.jks
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

      # Step 4: Build the release APK
      - name: Build release APK
        run: ./gradlew assembleRelease

      # Step 5: Sign the release APK
      - name: Sign APK
        run: |
          jarsigner -verbose \
            -sigalg SHA256withRSA \
            -digestalg SHA-256 \
            -keystore key.jks \
            -storepass ${{ secrets.KEYSTORE_PASSWORD }} \
            -keypass ${{ secrets.KEY_PASSWORD }} \
            app/build/outputs/apk/release/app-release-unsigned.apk \
            ${{ secrets.KEY_ALIAS }}

      # Step 6: Optimize APK with zipalign
      - name: Optimize APK with zipalign
        run: |
          $ANDROID_HOME/build-tools/*/zipalign -v -p 4 \
            app/build/outputs/apk/release/app-release-unsigned.apk \
            app/build/outputs/apk/release/app-release.apk

      # Step 7: Upload the signed APK as an artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk